export const POLLING_INTERVAL_DASHBOARD_SECONDS = 30;
export const POLLING_INTERVAL_DECLARE_ERRORS_SECONDS = 90;
export const POLLING_INTERVAL_DECLARE_HISTORY_SECONDS = 90;
export const POLLING_INTERVAL_INVOICES_SECONDS = 90;
export const POLLING_INTERVAL_MESSAGES_SECONDS = 30;
